services:
  - type: web
    name: hvac-app
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_CONNECTION_STRING
        fromSecret: MONGO_CONNECTION_STRING

